apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: deployment.yaml
- path: service.yaml

replicas:
- name: vote
  count: 8

images:
  - name: schoolofdevops/vote
    newTag: v5

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supportedBy: "lychnobyte.my.id"

configMapGenerator:
  - name: vote-options
    envs:
    - options.env
